/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuAyuda;

import InterfazOnePiece.Interfaz;
import VentasArtículos.InterfazVentas;
import javax.swing.JFrame;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Hugo
 */
public class TerminosCondiciones extends javax.swing.JFrame {
 private static TerminosCondiciones terminoscondiciones;
    /**
     * Creates new form TerminosCondiciones
     */
    private TerminosCondiciones() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setResizable(false);
    }
    public static TerminosCondiciones getInstance(){
        if(terminoscondiciones==null)
            terminoscondiciones=new TerminosCondiciones();
        return terminoscondiciones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cH_Aceptar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Términos y Condiciones One Piece v1.1\n");
        setMinimumSize(new java.awt.Dimension(700, 400));

        jLabel1.setBackground(new java.awt.Color(223, 230, 233));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÉRMINOS Y CONDICIONES");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnContinuar.setBackground(new java.awt.Color(223, 230, 233));
        btnContinuar.setText("Continuar al programa");
        btnContinuar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnContinuarStateChanged(evt);
            }
        });
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);

        btnSalir.setBackground(new java.awt.Color(223, 230, 233));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(223, 230, 233));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Este contrato describe los término y condiciones generables aplicados al uso del \nlos contenidos, produsctos y servicios ofrecidos através del software Tienda One Piece \nel cuál es titular.\nEs requisito necesario para la adquisición de los productos que se ofrecen en este\nsitio, que lea y acepte los siguientes Términos y Condiciones que a continuación se\nredactan. El uso de nuestros servicios así como la compra de nuestros productos\nimplicará que usted ha leído y aceptado los Términos y Condiciones de Uso en el\npresente documento. Todas los productos que son ofrecidos por nuestro sitio web\npudieran ser creadas, cobradas, enviadas o presentadas por una página web tercera y\nen tal caso estarían sujetas a sus propios Téminos y Condiciones. En algunos casos,\npara adquirir un producto, será necesario el registro por parte del usuario, con ingreso\nde datos personales.\nEste software e información van a ser usados única y exclusivamente para este establecimiento.");
        jTextArea1.setMinimumSize(new java.awt.Dimension(672, 500));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        cH_Aceptar.setBackground(new java.awt.Color(223, 230, 233));
        cH_Aceptar.setText("He leído y acepto los términos y condiciones");
        cH_Aceptar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cH_AceptarStateChanged(evt);
            }
        });
        jPanel3.add(cH_Aceptar);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnContinuarStateChanged
 
    }//GEN-LAST:event_btnContinuarStateChanged

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
Interfaz interfaz= Interfaz.getInstance();
        interfaz.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cH_AceptarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cH_AceptarStateChanged
       if(cH_Aceptar.isSelected()==false){
    btnContinuar.setEnabled(false);
} else{
    btnContinuar.setEnabled(true);
}    
    }//GEN-LAST:event_cH_AceptarStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cH_Aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
