/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazOnePiece;

import RegistrarCliente.MirarClientes;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class InicioSesion extends javax.swing.JFrame {

    private static InicioSesion iniciosesion;

    /**
     * Creates new form InicioSesion
     */
    private InicioSesion() {
        initComponents();
    }
     public static InicioSesion getInstance(){
        if(iniciosesion==null)
            iniciosesion=new InicioSesion();
        return iniciosesion;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda One Piece");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAyuda.setBackground(new java.awt.Color(204, 204, 204));
        btnAyuda.setText("Ayuda");
        btnAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAyudaMouseExited(evt);
            }
        });
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIngresarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnIngresarKeyReleased(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 160, 70));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 150, -1));

        txtUsuario.setText("Escriba su usuario");
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, 30));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblContraseña.setText("Contraseña :");
        jPanel2.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblUsuario.setText("Usuario :");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        lblicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazOnePiece/inicio sesion1.png"))); // NOI18N
        jPanel2.add(lblicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazOnePiece/fondo-azul-207702.jpg"))); // NOI18N
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2790, 1620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       String usuario="ADMIN";
       String contraseña="onepiece";
       String Pass= new String(jPasswordField1.getPassword());
       if(txtUsuario.getText().equals(usuario)&& Pass.equals(contraseña)){
           Interfaz interfaz= Interfaz.getInstance();
        interfaz.setVisible(true);
        this.dispose();
       }else{
           JOptionPane.showMessageDialog(null,"Usuario/contraseña incorrectos");
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
          
          txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
       jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void btnIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIngresarKeyPressed
    
    }//GEN-LAST:event_btnIngresarKeyPressed

    private void btnIngresarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIngresarKeyReleased

    }//GEN-LAST:event_btnIngresarKeyReleased

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "Usuario: ADMIN"+"\n"+"Contraseña: Nombre del anime sin espacio y minúsculas");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAyudaMouseExited
        btnAyuda.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_btnAyudaMouseExited

    private void btnAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAyudaMouseEntered
      btnAyuda.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnAyudaMouseEntered

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
      String usuario="ADMIN";
       String contraseña="onepiece";
       String Pass= new String(jPasswordField1.getPassword());
       if(txtUsuario.getText().equals(usuario)&& Pass.equals(contraseña)){
           Interfaz interfaz= Interfaz.getInstance();
        interfaz.setVisible(true);
        this.dispose();
       }else{
           JOptionPane.showMessageDialog(null,"Usuario/contraseña incorrectos");
       }
}
    }//GEN-LAST:event_jPasswordField1KeyReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblicono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
