/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistrarCliente;

import ControllerRegistroCLiente.ClientesController;
import DAOClientes.DAOclientes;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class EditarCliente extends javax.swing.JFrame {
 private static EditarCliente editarcliente;

    /**
     * Creates new form EditarCliente
     */
    private EditarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        String productos[]={"1 a 10 compras","11 a 20 compras","21 a 30 compras","31 o más compras"};
        String identificacion[]={"CC","TI","Pasaporte","Registro civil"};
DefaultComboBoxModel comboModel= new DefaultComboBoxModel(productos);
DefaultComboBoxModel comboModel2= new DefaultComboBoxModel(identificacion);
cboidentificacion.setModel(comboModel2);
cboCompras.setModel(comboModel);

    }
public static EditarCliente getInstance(){
        if(editarcliente==null)
            editarcliente=new EditarCliente();
        return editarcliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboCompras = new javax.swing.JComboBox<>();
        lblTítulo = new javax.swing.JLabel();
        JpanelNumeroDocumento = new javax.swing.JPanel();
        txtdocumento = new javax.swing.JTextField();
        jpanel1 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jpanelNombre2 = new javax.swing.JPanel();
        txtnombre2 = new javax.swing.JTextField();
        jpanelApellido = new javax.swing.JPanel();
        txtapellido = new javax.swing.JTextField();
        jpanelApellido2 = new javax.swing.JPanel();
        txtapellido3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cboidentificacion = new javax.swing.JComboBox<>();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Cliente One Piece v.1.1");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboCompras.setBackground(new java.awt.Color(223, 230, 233));
        cboCompras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboComprasActionPerformed(evt);
            }
        });
        jPanel1.add(cboCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        lblTítulo.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("ESCRIBA LOS NUEVOS DATOS DEL CLIENTE");
        jPanel1.add(lblTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        JpanelNumeroDocumento.setBackground(new java.awt.Color(223, 230, 233));
        JpanelNumeroDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de docmento:"));
        JpanelNumeroDocumento.setLayout(new java.awt.GridLayout(1, 0));

        txtdocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdocumentoMouseClicked(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        JpanelNumeroDocumento.add(txtdocumento);

        jPanel1.add(JpanelNumeroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 230, -1));

        jpanel1.setBackground(new java.awt.Color(223, 230, 233));
        jpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer Nombre"));
        jpanel1.setLayout(new java.awt.GridLayout(1, 0));

        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreMouseClicked(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jpanel1.add(txtnombre);

        jPanel1.add(jpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, -1));

        jpanelNombre2.setBackground(new java.awt.Color(223, 230, 233));
        jpanelNombre2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Nombre"));
        jpanelNombre2.setLayout(new java.awt.GridLayout(1, 0));

        txtnombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombre2MouseClicked(evt);
            }
        });
        txtnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre2ActionPerformed(evt);
            }
        });
        txtnombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre2KeyTyped(evt);
            }
        });
        jpanelNombre2.add(txtnombre2);

        jPanel1.add(jpanelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 230, -1));

        jpanelApellido.setBackground(new java.awt.Color(223, 230, 233));
        jpanelApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer Apellido"));
        jpanelApellido.setLayout(new java.awt.GridLayout(1, 0));

        txtapellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidoMouseClicked(evt);
            }
        });
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        jpanelApellido.add(txtapellido);

        jPanel1.add(jpanelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 230, -1));

        jpanelApellido2.setBackground(new java.awt.Color(223, 230, 233));
        jpanelApellido2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Apellido"));
        jpanelApellido2.setLayout(new java.awt.GridLayout(1, 0));

        txtapellido3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellido3MouseClicked(evt);
            }
        });
        txtapellido3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellido3KeyTyped(evt);
            }
        });
        jpanelApellido2.add(txtapellido3);

        jPanel1.add(jpanelApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Número de compras");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 190, 40));

        jButton1.setBackground(new java.awt.Color(223, 230, 233));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 130, -1));

        jButton2.setBackground(new java.awt.Color(223, 230, 233));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 190, 130, -1));

        cboidentificacion.setBackground(new java.awt.Color(223, 230, 233));
        cboidentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegistrarCliente/barco_onepiece.jpg"))); // NOI18N
        jPanel1.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 920, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre2ActionPerformed
public void Pordefecto(){
     txtnombre.setText("");
        txtnombre2.setText("");
        txtapellido.setText("");
        txtapellido3.setText("");
        txtdocumento.setText("");
        txtdocumento.setText("Solo números");
        
        //tipodocumento.setSelected((ButtonModel) rbtnCC, true);
        

}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       DAOclientes clientCont = ClientesController.getInstance();
        if(txtnombre.getText().equals("")||txtnombre.getText().equals("OBLIGATORIO")||txtnombre.getText().equals("ESCRIBA AQUÍ")||
                txtapellido.getText().equals("")||txtapellido.getText().equals("OBLIGATORIO")||txtapellido.getText().equals("ESCRIBA AQUÍ")||
                        txtapellido3.getText().equals("")||txtapellido3.getText().equals("OBLIGATORIO")||txtapellido3.getText().equals("ESCRIBA AQUÍ")||
                                txtdocumento.getText().equals("")||txtdocumento.getText().equals("OBLIGATORIO")||txtdocumento.getText().equals("Sólo números"))
                                        {
                                            
           jpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre : **", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51)));
            txtnombre.setForeground(new java.awt.Color(255, 0, 51));
            //txtNombCliente.setText("OBLIGATORIO");
            
            //txtNombCliente2.setText("");
            
            JpanelNumeroDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número Documento : **", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51)));
            txtdocumento.setForeground(new java.awt.Color(255, 0, 51));
            //txtdocumento.setText("OBLIGATORIO");
            
            jpanelApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido : **", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51)));
            txtapellido.setForeground(new java.awt.Color(255, 0, 51));
            //txtApellido2.setText("OBLIGATORIO");
            
            jpanelApellido2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segundo Apellido : **", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51)));
            txtapellido3.setForeground(new java.awt.Color(255, 0, 51));
            //txtApellido1.setText("OBLIGATORIO");
           
             //JpanelTipoDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Documento de Identidad : **", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51)));    
                
           
             
           JOptionPane.showMessageDialog(null,"Rellene las casillas en rojo");  
        }else{
         
        String nombCliente= txtnombre.getText().toUpperCase();
        String nombCliente2= txtnombre2.getText().toUpperCase();
        String ApeCliente=txtapellido3.getText().toUpperCase();
        String ApeCliente2=txtapellido.getText().toUpperCase();
        

//"CC","TI","Pasaporte","Registro civil"
         String TI="";
         String itemSeleccionado2 = (String)cboidentificacion.getSelectedItem();
         if("CC".equals(itemSeleccionado2)){
             TI="Cédula de ciudadanía";
         }
       if("TI".equals(itemSeleccionado2)){
           TI="Tarjeta de identidad";
       }
       if("Pasaporte".equals(itemSeleccionado2)){
           TI="Pasaporte";
       }
       if("Registro civil".equals(itemSeleccionado2)){
           TI="Registro civil";
       }
        String numident=txtdocumento.getText();
        String NCM="";
        String itemSeleccionado = (String)cboCompras.getSelectedItem();
        if("1 a 10 compras".equals(itemSeleccionado)){
            NCM="1 a 10 compras";
        }else{
            if("11 a 20 compras".equals(itemSeleccionado)){
                NCM="11 a 20 compras";
            }else{
                if("21 a 30 compras".equals(itemSeleccionado)){
                    NCM="21 a 30 compras";
                }else{
                    if("31 o más compras".equals(itemSeleccionado)){
                        NCM="31 o más compras";
                    }
                }
            }
        }
            
      String[] cliente={ApeCliente2, ApeCliente,nombCliente,nombCliente2 , TI,numident, NCM};
      
      clientCont.ActualizarCliente(cliente);
      JOptionPane.showMessageDialog(null,"Se han actualizado los datos de el cliente");
      MirarClientes mirarclientes= MirarClientes.getInstance();
        mirarclientes.setVisible(true);
        this.dispose();
 
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    public void datosPorActualizar(String[] cliente){
        txtapellido.setText(cliente[0]);
        txtapellido3.setText(cliente[1]);
        txtnombre.setText(cliente[2]);
        txtnombre2.setText(cliente[3]);
        txtdocumento.setText(cliente[5]);
        
        
        
        
        
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MirarClientes mirarclientes= MirarClientes.getInstance();
        mirarclientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
   int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    
            
     if (!(mayusculas )&&!(minusculas))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre2KeyTyped
      int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    
            
     if (!(mayusculas )&&!(minusculas))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtnombre2KeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
       int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    
            
     if (!(mayusculas )&&!(minusculas))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtapellido3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellido3KeyTyped
       int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    
            
     if (!(mayusculas )&&!(minusculas))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtapellido3KeyTyped

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
     if(!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void txtnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMouseClicked
       txtnombre.setText("");
    }//GEN-LAST:event_txtnombreMouseClicked

    private void txtnombre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombre2MouseClicked
       txtnombre2.setText("");
    }//GEN-LAST:event_txtnombre2MouseClicked

    private void txtapellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoMouseClicked
        txtapellido.setText("");
    }//GEN-LAST:event_txtapellidoMouseClicked

    private void txtapellido3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellido3MouseClicked
        txtapellido3.setText("");
    }//GEN-LAST:event_txtapellido3MouseClicked

    private void txtdocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdocumentoMouseClicked
        txtdocumento.setText("");
    }//GEN-LAST:event_txtdocumentoMouseClicked

    private void cboComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboComprasActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelNumeroDocumento;
    private javax.swing.JComboBox<String> cboCompras;
    private javax.swing.JComboBox<String> cboidentificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JPanel jpanelApellido;
    private javax.swing.JPanel jpanelApellido2;
    private javax.swing.JPanel jpanelNombre2;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellido3;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre2;
    // End of variables declaration//GEN-END:variables
}
