/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistrarCliente;

import ControllerRegistroCLiente.ClientesController;
import DAOClientes.DAOclientes;
import InterfazOnePiece.Interfaz;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hugo
 */
public class MirarClientes extends javax.swing.JFrame {
      private static MirarClientes instancia=null;
    private DefaultTableModel modelo;
     /**
     * Creates new form MirarClientes
     */
     
    private MirarClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void ActuListaClientes(){
        DAOclientes pokCont = ClientesController.getInstance();
        modelo=pokCont.MostrarClientes();
        jTable1.setModel(modelo);
    }
    
    public static MirarClientes getInstance(){
        if(instancia==null)
            instancia=new MirarClientes();
        instancia.ActuListaClientes();
        return instancia;
    }

   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista One Piece v1.1");

        jLabel1.setBackground(new java.awt.Color(223, 230, 233));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista Clientes One Piece");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setBackground(new java.awt.Color(223, 230, 233));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(223, 230, 233));
        jButton1.setText("Agregar Nuevo Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(223, 230, 233));
        jButton2.setText("Actualizar Lista Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton4.setBackground(new java.awt.Color(223, 230, 233));
        jButton4.setText("Eliminar Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(223, 230, 233));
        jButton5.setText("Editar Cliente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        btnguardar.setBackground(new java.awt.Color(223, 230, 233));
        btnguardar.setText("Guardar txt");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar);

        btnSubir.setBackground(new java.awt.Color(223, 230, 233));
        btnSubir.setText("Subir Archivo");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubir);

        jButton3.setBackground(new java.awt.Color(223, 230, 233));
        jButton3.setText("Regresar al Menú");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.ActuListaClientes();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegistrarCliente interfaz = RegistrarCliente.getInstance();
       interfaz.setVisible(true);
       this.dispose();
      // JOptionPane.showMessageDialog(null,"Recuerde activar las letras MAYÚSCULAS");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          Interfaz interfaz = Interfaz.getInstance();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try
       {
          ClientesController cliente= ClientesController.getInstance();
            int codigo;
        
            codigo=jTable1.getSelectedRow();
            if(!String.valueOf(codigo).equals(null))
            {
                cliente.EliminarCliente(codigo);
            jTable1.setModel(cliente.MostrarClientes());
            
            }
            
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "selecciona un elemento");
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        try{
            if(jTable1.getSelectedRow()>=0){
                String seleccionTxt=""+modelo.getValueAt(jTable1.getSelectedRow(),jTable1.getSelectedColumn());
                
                if(!seleccionTxt.equals("null")){
                    
                    String[] cliente=new String[7];
                    for(int i=0;i<7;i++){
                        cliente[i]=modelo.getValueAt(jTable1.getSelectedRow(),i).toString();
                    }
                    EditarCliente editar = EditarCliente.getInstance();
                    editar.setVisible(true);
                    editar.Pordefecto();
                  editar.datosPorActualizar(cliente);
                    this.dispose();
                    System. out. println("ES"+seleccionTxt);
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un campo no vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debe seleccionar un elemento", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        DAOclientes cliCont = ClientesController.getInstance();
        if(cliCont.GuardarArchivo()){
            JOptionPane.showMessageDialog(null,"Guardado Exitoso");
        }else{
            JOptionPane.showMessageDialog(null,"Error al guardar");
    }
    
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
            DAOclientes usuCon = ClientesController.getInstance();
        JFileChooser fileUsu = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "Documento de texto (*.txt)", "txt");
        fileUsu.setFileFilter(filter);
        int returnVal = fileUsu.showOpenDialog(rootPane);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String archivo = fileUsu.getSelectedFile().toString();
            
            if(usuCon.SubirArchivo(archivo))
                ActuListaClientes();
            
        }
        ActuListaClientes();
    }//GEN-LAST:event_btnSubirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
