/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistrarCliente;

import ControllerRegistroCLiente.ClientesController;
import DAOClientes.DAOclientes;
import InterfazOnePiece.Interfaz;

/**
 *
 * @author Hugo
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    private static RegistrarCliente registrarCliente;
    /**
     * Creates new form AgregarPokemon
     */
    private RegistrarCliente() {
        initComponents();
    }
    
    public static RegistrarCliente getInstance(){
        if(registrarCliente == null)
            registrarCliente=new RegistrarCliente();
        return registrarCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombCliente = new javax.swing.JTextField();
        jPanelApellido2 = new javax.swing.JPanel();
        txtApellido = new javax.swing.JTextField();
        JpanelTipoDocumento = new javax.swing.JPanel();
        cH_CC = new javax.swing.JCheckBox();
        cH_Otro = new javax.swing.JCheckBox();
        JpanelNumeroDocumento = new javax.swing.JPanel();
        txtdocumento = new javax.swing.JTextField();
        jPanelNombre2 = new javax.swing.JPanel();
        txtNombCliente2 = new javax.swing.JTextField();
        jPanelApellido = new javax.swing.JPanel();
        txtApellido2 = new javax.swing.JTextField();
        jPanelPromedioCompras = new javax.swing.JPanel();
        cH_uno = new javax.swing.JCheckBox();
        cH_11 = new javax.swing.JCheckBox();
        cH_21 = new javax.swing.JCheckBox();
        cH_31 = new javax.swing.JCheckBox();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre :"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        txtNombCliente.setText("Escriba aquí");
        txtNombCliente.setBorder(null);
        txtNombCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombClienteMouseClicked(evt);
            }
        });
        txtNombCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombCliente);

        jPanelApellido2.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido 2:"));
        jPanelApellido2.setLayout(new java.awt.GridLayout(1, 0));

        txtApellido.setText("Escriba aquí");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        jPanelApellido2.add(txtApellido);

        JpanelTipoDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Documento de Identidad"));
        JpanelTipoDocumento.setLayout(new java.awt.GridLayout(1, 0));

        cH_CC.setText("Cédula de ciudadania");
        JpanelTipoDocumento.add(cH_CC);

        cH_Otro.setText("Otro");
        cH_Otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cH_OtroActionPerformed(evt);
            }
        });
        JpanelTipoDocumento.add(cH_Otro);

        JpanelNumeroDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder("Número Documento"));
        JpanelNumeroDocumento.setLayout(new java.awt.GridLayout(1, 0));

        txtdocumento.setText("Solo números");
        txtdocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdocumentoMouseClicked(evt);
            }
        });
        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        JpanelNumeroDocumento.add(txtdocumento);

        jPanelNombre2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre 2 :"));
        jPanelNombre2.setLayout(new java.awt.GridLayout(1, 0));

        txtNombCliente2.setText("Opcional");
        txtNombCliente2.setBorder(null);
        txtNombCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombCliente2MouseClicked(evt);
            }
        });
        txtNombCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombCliente2ActionPerformed(evt);
            }
        });
        jPanelNombre2.add(txtNombCliente2);

        jPanelApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        jPanelApellido.setLayout(new java.awt.GridLayout(1, 0));

        txtApellido2.setText("Escriba aquí");
        txtApellido2.setBorder(null);
        txtApellido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellido2MouseClicked(evt);
            }
        });
        jPanelApellido.add(txtApellido2);

        jPanelPromedioCompras.setBorder(javax.swing.BorderFactory.createTitledBorder("Número Compras Mensuales"));

        cH_uno.setText("1-10");
        cH_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cH_unoActionPerformed(evt);
            }
        });

        cH_11.setText("11-20");

        cH_21.setText("21-30");

        cH_31.setText("31 o más");

        javax.swing.GroupLayout jPanelPromedioComprasLayout = new javax.swing.GroupLayout(jPanelPromedioCompras);
        jPanelPromedioCompras.setLayout(jPanelPromedioComprasLayout);
        jPanelPromedioComprasLayout.setHorizontalGroup(
            jPanelPromedioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPromedioComprasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelPromedioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cH_31, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cH_21, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cH_11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cH_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelPromedioComprasLayout.setVerticalGroup(
            jPanelPromedioComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPromedioComprasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(cH_uno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cH_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cH_21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cH_31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar Cliente");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Datos");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jPanelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jPanelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JpanelTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelPromedioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JpanelNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JpanelTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JpanelNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanelPromedioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombClienteActionPerformed

    private void cH_OtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cH_OtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cH_OtroActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    private void txtNombCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombCliente2ActionPerformed

    private void cH_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cH_unoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cH_unoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         Interfaz interfaz = Interfaz.getInstance();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
         DAOclientes clientCont = ClientesController.getInstance();
        String nombCliente= txtNombCliente.getText();
        String nombCliente2= txtNombCliente2.getText();
        String ApeCliente=txtApellido.getText();
        String ApeCliente2=txtApellido2.getText();
        String TI="";
        if (cH_CC.isSelected()){
            TI=" Cédula de Ciudadanía";
        }else{
            if(cH_Otro.isSelected()){
            TI="Otro";
        }
        }
        String numident=txtdocumento.getText();
        String NCM="";
        if(cH_uno.isSelected()){
            NCM="1 a 10 compras";
        }else{
            if(cH_11.isSelected()){
                NCM="11 a 20 compras";
            }else{
                if(cH_21.isSelected()){
                    NCM="21 a 30 compras";
                }else{
                    if(cH_31.isSelected()){
                        NCM="31 o más compras";
                    }
                }
            }
        }
            
      clientCont.AgregarCliente(ApeCliente, ApeCliente2,nombCliente,nombCliente2 , TI,numident, NCM);
        
         
         
                
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNombClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombClienteMouseClicked
        // TODO add your handling code here:
        txtNombCliente.setText("");
    }//GEN-LAST:event_txtNombClienteMouseClicked

    private void txtNombCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombCliente2MouseClicked
        // TODO add your handling code here:
        txtNombCliente2.setText("");
    }//GEN-LAST:event_txtNombCliente2MouseClicked

    private void txtApellido2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellido2MouseClicked
        // TODO add your handling code here:
        txtApellido2.setText("");
    }//GEN-LAST:event_txtApellido2MouseClicked

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        // TODO add your handling code here:
        txtApellido.setText("");
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtdocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdocumentoMouseClicked
        // TODO add your handling code here:
        txtdocumento.setText("");
    }//GEN-LAST:event_txtdocumentoMouseClicked

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        // TODO add your handling code here:
          if(!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_txtdocumentoKeyTyped

    /**
     *
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelNumeroDocumento;
    private javax.swing.JPanel JpanelTipoDocumento;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox cH_11;
    private javax.swing.JCheckBox cH_21;
    private javax.swing.JCheckBox cH_31;
    private javax.swing.JCheckBox cH_CC;
    private javax.swing.JCheckBox cH_Otro;
    private javax.swing.JCheckBox cH_uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelApellido;
    private javax.swing.JPanel jPanelApellido2;
    private javax.swing.JPanel jPanelNombre2;
    private javax.swing.JPanel jPanelPromedioCompras;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtNombCliente;
    private javax.swing.JTextField txtNombCliente2;
    private javax.swing.JTextField txtdocumento;
    // End of variables declaration//GEN-END:variables
}
